### PR TITLE
Rdd string

### PR DESCRIPTION
**Pull request by pjfanning**
Relates to https://github.com/databricks/spark-csv/issues/188

### CODE REVIEW

**Comment by falaki** [comment]
The implicit functions in `package.scala` are not going to be updated in future. Users are encouraged to use spark's `load` and `save` API to interact with spark-csv rather than directly calling the implicit functions.

**Comment by Tagar** [comment]
Thank you. Which spark-csv version this PR will be part of?

**Comment by falaki** [comment]
load and save functions exist in all Spark 1.4+ versions.

**Comment by Tagar** [comment]
I was asking regarding "adds a csvRdd function to create a Dataframe from RDD[String]".
Please check https://github.com/databricks/spark-csv/issues/264
Thanks.

**Pull request closed without merging**
