### PR TITLE
Tokens not added for index safety when their number exceeds the number of fields in schema. 

### PR DESCRIPTION
**Pull request by HyukjinKwon**
When the number of `tokens` is larger than  the number of`schema.fields`, then it throws `NegativeArraySizeException` as below.

```bash
java.lang.NegativeArraySizeException
    at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:171)
    at com.databricks.spark.csv.CsvRelation$$anonfun$buildScan$6.apply(CsvRelation.scala:162)
    at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:148)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
    at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

This was reported in Spark as well, https://issues.apache.org/jira/browse/SPARK-13114.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
This is already fixed in Spark but for this it is not. Simply copied the one in Spark.

**Comment by falaki** [comment]
Thanks @HyukjinKwon for submitting this. It looks good.

**Comment by HyukjinKwon** [comment]
@falaki Then could we maybe merge this?

**Comment by falaki** [comment]
LGTM

**Pull request closed without merging**
