### PR TITLE
fix error no serializable task on cluster mode

### PR DESCRIPTION
**Pull request by QiangCai**
on cluster mode,   baseRDD method trigger no serializable task exception

### CODE REVIEW

**Comment by QiangCai** [comment]
retest this please

**Comment by QiangCai** [comment]
@falaki please review

**Comment by HyukjinKwon** [comment]
@QiangCai It seems some tests were failed.

**Comment by QiangCai** [comment]
@HyukjinKwon can you help me to resolve test error?

**Comment by QiangCai** [comment]
@HyukjinKwon  @falaki I have to go back version 1.2 to avoid this issue of version 1.3/1.4.

**Comment by falaki** [comment]
@QiangCai your patch is failing a unit test: SQL test insert overwrite for all versions of Spark.

**Pull request closed without merging**
