### PR TITLE
Make type inference recognize boolean types

### PR DESCRIPTION
**Pull request by yucheng1992**
This pull request is to make the type inference recognize Boolean types like "True" or "False", and I have added some unit tests for inferring the boolean type.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
I will like the issue link here. https://github.com/databricks/spark-csv/issues/207

**Comment by HyukjinKwon** [comment]
To make this clear, this PR would support infer case-insensitive `true` as `BooleanType`.

**Comment by HyukjinKwon** [comment]
Don't we need a end-to-end test at `CsvSuite`? (As you might know, ` case BooleanType => tryParseBoolean(field)` is not being tested, [Codecov#InferSchema](https://codecov.io/github/databricks/spark-csv/commit/35f17ac13b8cbebd6a04a7f807077cc8f0d11340))

**Comment by yl2695** [comment]
Do you mean if an item in a row is "TRUE", we'll infer it as StringType instead of BooleanType?

**Comment by yl2695** [comment]
Sure, I'll add the unit tests later. Thanks.

**Comment by falaki** [comment]
@yucheng1992 this is a good feature to have. Would you please rebase it?

**Comment by yucheng1992** [comment]
@falaki Rebased. Thanks!

**Pull request closed without merging**
