### PR TITLE
Add support for specifying a compression codec when saving

### PR DESCRIPTION
**Pull request by pashields**
Didn't see any existing tests to update. Did I miss anything?

### CODE REVIEW

**Comment by falaki** [comment]
Thanks @pashields. Two suggestions:
1. Add tests for this
2. I think compression can be an option to save(). If you are interested look into ```CreatableRelationProvider``` in Spark 1.3 and add support for that?

**Comment by falaki** [comment]
Thanks @pashields this looks good. Would you please rebase it? I am going to cut v1.0.1 with this.

**Comment by pashields** [comment]
Yeah, I will hide my shame with a rebase. I'm still looking at adding support in ```save()```, but I'm new to scala and spark so let's not hold this up for that.

I'll push in a minute.

**Comment by pashields** [comment]
Ok, should be good @falaki. Thanks for your help with the PR.

**Pull request merged**
