### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarkRijckenberg**
Reason for pull request:  see   https://github.com/databricks/spark-csv/issues/38

### CODE REVIEW

**Comment by falaki** [comment]
Thanks!

**Comment by rxin** [comment]
Maybe Spark's data source API should convert common Python types back into proper Strings. 

@davies can we add that?

**Comment by rxin** [comment]
I filed https://issues.apache.org/jira/browse/SPARK-6591 for this.

**Comment by MarkRijckenberg** [comment]
Thanks for filing the bug report at https://issues.apache.org/jira/browse/SPARK-6591

However, please keep in mind that the whole issue is a little broader than only converting   header = True  to header="true"

If you follow my procedure here:

https://mark911.wordpress.com/2015/03/21/how-to-build-pysparkmaven-and-apache-spark-from-github-sources-using-a-bash-script-in-ubuntu-14-04-lts-64-bit/

and you leave out source= or header= or leave out path = or if you use header="True" or any combination of these , the command will still not work. So the use of header="true" is case sensitive in Ubuntu. And the use of source=  , header= and path= is apparently required...

The rules to getting

df = sqlContext.load(source="com.databricks.spark.csv", header="true",path = "cars.csv")

to work are stricter - at least in Ubuntu -  than just converting the Python type back into Strings.

**Comment by rxin** [comment]
I was not suggesting the Spark load API will fix this. I was merely saying we should make it more convenient for users.

**Pull request merged**
