### PR TITLE
Bumping up version of spark packages plugin

### PR DESCRIPTION
**Pull request by falaki**
Using latest version of spark packages sbt plugin (0.2.1)

### CODE REVIEW

**Comment by brkyvz** [comment]
@falaki 
Could you please update the following in the build file?
 - `sparkPackageName` -> `spName` // sparkPackageName is deprecated
 - Remove [this line](https://github.com/databricks/spark-csv/blob/464a3e09529d97cdbb7f74b3d1bb5767c3c27ca2/build.sbt#L11). This is handled [here](https://github.com/databricks/spark-csv/blob/464a3e09529d97cdbb7f74b3d1bb5767c3c27ca2/build.sbt#L58)
 - add the line: `spAppendScalaVersion := true`

Thanks!

**Comment by falaki** [comment]
@brkyvz Thanks! Did we fix the bug in spark-packages.org with respect o appended scala version?

**Comment by brkyvz** [comment]
In Review. I'll ping Xiangrui tonight

**Comment by brkyvz** [comment]
@falaki the bug in spark-packages.org should be fixed now

**Comment by falaki** [comment]
@brkyvz Would you please take a look.

**Comment by brkyvz** [comment]
@falaki You can also include the option
`spIncludeMaven := true`
to include the original Maven coordinate (`com.databricks:spark-csv_2.11:v`) when publishing to Spark Packages. Then, you will need to publish to Maven Central first, before publishing to Spark Packages.

**Pull request merged**
