### PR TITLE
Deprecated DecimalType.Unlimited val was removed in Spark 2.0.0

### PR DESCRIPTION
**Pull request by jaceklaskowski**
See https://github.com/apache/spark/commit/77ab49b8575d2ebd678065fa70b0343d532ab9c2#diff-562cf76d70c7e4f4b4d163b13f67e337L126

### CODE REVIEW

**Comment by jaceklaskowski** [comment]
Why does travis execute tests for 1.4.1?

**Comment by falaki** [comment]
Hi @jaceklaskowski. Spark-csv is supposed to be backwards compatible so we test for different versions of Spark. Also note that in Spark 2.0 spark-csv was inlined. In other words, you don't need spark-csv to read CSV data in spark 2.0.

**Comment by jaceklaskowski** [comment]
Thanks @falaki! Why 1.4.1? It's **four** versions old - 1.6.0 / 1.5.2 / 1.5.1 / 1.5.0. I'd assume **1.5.0** being the latest (which would change nothing re the pull request, i.e. it'd fail anyway).

I didn't know about csv being inlined in 2.0. I seem to have missed that. Do you know what commit was that?

**Comment by falaki** [comment]
https://github.com/apache/spark/pull/10615

**Comment by HyukjinKwon** [comment]
Then does that mean closing this?

**Pull request closed without merging**
